services:
#================================
#Lancer le bus Kafka
#================================
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    networks:
      - insa-bridge
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      # Listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      # Settings for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    # Vérification de la santé de Kafka -> nécessaire pour que les autres services attendent que Kafka soit prêt
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
      
#================================
#Lancer postgresQl
#================================
  pg-insa:
    container_name: pg-insa
    build:
      context: ./pg-insa
    image: pg-insa:latest
    networks:
      - insa-bridge
    hostname: pg-insa
    restart: always
    ports:
      - "5433:5432"
    environment:
      - TZ=CET
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=insa
      - POSTGRES_HOST_AUTH_METHOD=trust
      # ne pas oublier de parameter le volume de postgresql sur disque lvm
    volumes:
      - ./pgdata:/var/lib/postgresql/data


#================================
#Lancer le service d'intégration
#================================
  integration-services:
    container_name: integration-services
    build:
      context: ./integration_services
      dockerfile: DockerHub/Dockerfile
    image: integration_services:latest
    networks:
      - insa-bridge
    depends_on:
      kafka:
        condition: service_healthy
      pg-insa:
        condition: service_started
    hostname: integration-services
    restart: always
    environment:
      # Surcharge des propriétés pour Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg-insa:5432/insa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:19092


#================================
#Lancer le service ws template
#================================
  ws-template:
    container_name: ws-template
    build:
      context: ./ws_services_template
      dockerfile: DockerHub/Dockerfile
    image: ws_services_template:latest
    networks:
      - insa-bridge
    depends_on:
      - kafka
      - pg-insa
    hostname: ws-template
    restart: always
    ports:
      - "8800:8800"
    environment:
      # Configuration Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      # Connection BDD pour validation API key uniquement
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg-insa:5432/insa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

#================================
# Lancer le front consult
#================================
  front-consult:
    container_name: front-consult
    image: front-consult:latest
    build: ./front-consult
    ports:
      - "8080:8080"
    networks:
      - insa-bridge
    depends_on:
      kafka:
        condition: service_healthy
      ws-template:
        condition: service_started
      integration-services:
        condition: service_started
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=kafka:19092
      - KAFKA_RESPONSE_TOPIC=students-response
      - API_URL=http://ws-template:8800
    restart: always


#renommer le réseau par defaut des services
networks:
    insa-bridge:
      name: insa-bridge
