services:
#================================
#Lancer le bus Kafka
#================================
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    networks:
      - insa-bridge
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      # Listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      # Settings for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
      
#================================
#Lancer postgresQl
#================================
  pg-insa:
    container_name: pg-insa
    image: pg-insa:latest
    command: postgres -c 'max_connections=200'
    networks:
      - insa-bridge
    hostname: pg-insa
    restart: always
    ports:
      - "5432:5432"
    environment:
      - TZ=CET
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=insa
      - POSTGRES_HOST_AUTH_METHOD=trust
      # ne pas oublier de parameter le volume de postgresql sur disque lvm
    volumes:
      - ./pgdata:/var/lib/postgresql/data


#================================
#Lancer le service d'intégration
#================================
  integration-services:
    depends_on:
      kafka:
        condition: service_started
      pg-insa:
        condition: service_started
    container_name: integration-services
    image: integration_services:latest
    networks:
      - insa-bridge
    hostname: integration-services
    restart: always
    environment:
      # Surcharge des propriétés pour Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg-insa:5432/insa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:19092


#================================
#Lancer le service ws template
#================================
# TODO : Modifier pour supprimer la dépendance à pg-insa 
# -> la BDD et l'API doivent être séparées
  # ws-template:
  #   depends_on:
  #     - pg-insa
  #   container_name: ws-template
  #   image: ws_services_template:latest
  #   networks:
  #     - insa-bridge
  #   hostname: ws-template
  #   restart: always
  #   ports:
  #     - "8800:8800"

#renommer le réseau par defaut des services
networks:
    insa-bridge:
      name: insa-bridge
