# Kubernetes configuration for integration-services

apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-services
  namespace: architecture-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-services
  template:
    metadata:
      labels:
        app: integration-services
    spec:
      containers:
        - name: integration-services
          image: alexispgn/integration_services:1.0
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://pg-insa:5432/insa"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"