# Kubernetes configuration for Kafka

# Service to expose Kafka : 
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: architecture-eda
spec:
  selector:
    app: kafka
  ports:
    - port: 9092


# StatefulSet to deploy Kafka with a mount
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: architecture-eda
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
          env:
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
          - name: KAFKA_ADVERTISED_LISTENERS
            value: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
          - name: KAFKA_LISTENERS
            value: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
          - name: KAFKA_NODE_ID
            value: 1
          - name: KAFKA_PROCESS_ROLES
            value: 'broker,controller'
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: 'PLAINTEXT'
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: 'CONTROLLER'
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: '1@kafka:29093'
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: 1
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            value: 0
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: 1
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: 1
          - name: KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR
            value: 1
          - name: KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR
            value: 1
          - name: CLUSTER_ID
            value: '4L6g3nShT-eMCtK--X86sw'
          - name: KAFKA_LOG_DIRS
            value: '/tmp/kraft-combined-logs'
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      
